### ISSUE TITLE
No code on master?

### ISSUE THREAD

**Issue by aninrusimha** [pmichel31415/are-16-heads-really-better-than-1#1]
In the README, it asks us to checkout a branch not put on master.  I don't think that branch is uploaded to master, as the github has no actual code in it.

**Comment by pmichel31415** [comment]
Aah sorry I realise the instructions are confusing. You should checkout this branch in the pytorch-pretrained-BERT folder.

Also you are right that I forgot to upload the experiment files. I just uploaded them. Let me know if you run into any issues.
