### ISSUE TITLE
Not able to obtain pretrained WMT model 

### ISSUE THREAD

**Issue by marwash25** [pmichel31415/are-16-heads-really-better-than-1#4]
Hello,

I am trying to run the MT ablation experiments. When I ran the command 

`wget https://s3.amazonaws.com/fairseq-py/models/wmt14.en-fr.joined-dict.transformer.tar.bz2`

I get the following error

`--2020-03-31 17:58:31--  https://s3.amazonaws.com/fairseq-py/models/wmt14.en-fr.joined-dict.transformer.tar.bz2
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.207.205
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.207.205|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-03-31 17:58:31 ERROR 404: Not Found.`

**Comment by pmichel31415** [comment]
Thanks for pointing ths out, looks like they moved the models. I think this link: https://dl.fbaipublicfiles.com/fairseq/models/wmt14.en-fr.joined-dict.transformer.tar.bz2 should work. Let me know if it doesn't, and I'll see if I can mirror the old checkpoint myself.

**Comment by marwash25** [comment]
yes this one works, thank you!
