### ISSUE TITLE
a question about run_classifier.py

### ISSUE THREAD

**Issue by Ixuanzhang** [pmichel31415/are-16-heads-really-better-than-1#5]
1、
(1)I do this and get a pruned model:
    model.bert.prune_heads(to_prune)
(2) I set n_retrain_steps_after_pruning a value greater than 0
    next：
![aaa](https://user-images.githubusercontent.com/8215764/88050045-b885f900-cb88-11ea-8532-58a9a33fe792.png)
     then:
      
![bbb](https://user-images.githubusercontent.com/8215764/88050074-c3408e00-cb88-11ea-9e1e-a236df576a8a.png)

      to retrain my pruned model, that is ok?

2、I don't understand the difference between above method and retrain_pruned_heads（the following method）
  
![cccc](https://user-images.githubusercontent.com/8215764/88050267-161a4580-cb89-11ea-89ff-477d53b54ad4.png)

THANK YOU !

**Comment by pmichel31415** [comment]
Sorry for the late reply, did you figure this out?
